### ISSUE TITLE
Rendering issues with Safari

### ISSUE THREAD

**Issue by udeyrishi** [ahoskins/grind#2]
Safari is not rendering the three columns properly.
<img width="1159" alt="screen shot 2015-09-21 at 10 44 14 am" src="https://cloud.githubusercontent.com/assets/4692593/9998302/b7eae074-604d-11e5-95db-9ba806e81da0.png">

**Comment by udeyrishi** [comment]
Issue seems to affect only OS X Safari

**Comment by ahoskins** [comment]
closed in d8acbee18b2b18c79c401f3c01a2733e1f54c3f5
